### PR TITLE
LT-113: Allow use of Sidekiq as well as Resque

### PR DESCRIPTION
**Pull request by gregbeech**
*Still TODO: Update the docs to indicate either Sidekiq or Resque can be used, and add some more test coverage.*

This PR allows use of different job engine backends, with either Sidekiq or Resque supported. It's a bit "involved" seeing as it was sticking to the following constraints:

* Don't just dump Resque support as we still use it in some projects
* Don't use ActiveJob as some projects are still on Rails 3.x

As such it takes the approach of using an "ActiveJob-lite" style pluggable backend, just reimplementing the parts that are needed.

The default is still Resque, so it's almost entirely backwards compatible. The only slight incompatibility is that the job backend initializer will need to include the line of code to preload the relevant job bits, e.g.

```ruby
# config/initializers/routemaster.rb

require 'routemaster/jobs/backends/sidekiq'
```

### CODE REVIEW

**Review by rfonglip — COMMENTED** [review]
So far it looks good to me 👍

**Comment by mezis** [comment]
Looks good. I think we'd want an end-to-end test — actually running the Sidekiq or Resque runtime, possibly inline, and executing a job?

**Comment by gregbeech** [comment]
@mezis I've added some tests that the backends actually pass through the arguments correctly and execute jobs using the inline versions of Sidekiq/Resque. I know you don't like `around` blocks but they're the appropriate way to handle this kind of thing IMHO.

**Comment by mezis** [comment]
Looks all good. 🚢  it!

**Pull request merged**
